/*
 Navicat Premium Data Transfer

 Source Server         : Localhost
 Source Server Type    : MySQL
 Source Server Version : 80030
 Source Host           : localhost:3306
 Source Schema         : cinema4

 Target Server Type    : MySQL
 Target Server Version : 80030
 File Encoding         : 65001

 Date: 28/11/2022 20:13:14
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for login
-- ----------------------------
DROP TABLE IF EXISTS `login`;
CREATE TABLE `login`  (
  `id` int NOT NULL,
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `roles` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of login
-- ----------------------------
INSERT INTO `login` VALUES (1, 'rack', '1234', 'admin');
INSERT INTO `login` VALUES (2, 'juan', '4321', 'user');

-- ----------------------------
-- Table structure for movies
-- ----------------------------
DROP TABLE IF EXISTS `movies`;
CREATE TABLE `movies`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_movie` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `genre` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `description` varchar(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `director` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `trailer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `official_site` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 51 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of movies
-- ----------------------------
INSERT INTO `movies` VALUES (1, 'tt0068646', 'The Godfather', 'Drama', 'The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter\'s wedding. Michael, Vito\'s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be.com/embed uninterested in be.com/embeding a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don\'s influence for the same, Vito refuses to do it. What follows is a clash be.com/embedtween Vito\'s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.', 'United States', 'Francis Ford Coppola', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'https://www.youtube.com/embed/gCVj1LeYnsc', 'https://www.facebook.com/thegodfather/', '2014-11-22 14:11:22');
INSERT INTO `movies` VALUES (3, 'tt0167260', 'The Lord of the Rings: The Return of the King', 'Fantasy', 'The final confrontation be.com/embedtween the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron\'s evil army at the stone city of Minas Tirith.', 'United States', 'Peter Jackson', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'https://www.youtube.com/embed/JB7fjEtzrsk', 'https://youtube.com/embed/V75dMMIW2B4', '2003-10-22 14:11:23');
INSERT INTO `movies` VALUES (4, 'tt9114286', 'Black Panther: Wakanda Forever', 'Action', 'Queen Ramonda, Shuri, M\'Baku, Okoye and the Dora Milaje fight to protect the kingdom of Wakanda from intervening world powers in the wake of King T\'Challa\'s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for their nation.', 'United States', 'Ryan Coogler', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sv1xJUazXeYqALzczSZ3O6nkH75.jpg', 'https://youtube.com/embed/INvxJD4FzLk', 'https://www.facebook.com/BlackPantherMovie/', '2022-10-22 15:11:24');
INSERT INTO `movies` VALUES (5, 'tt6443346', 'Black Adam', 'Action', 'Nearly 5,000 years after he was be.com/embedstowed with the almighty powers of the Egyptian gods--and imprisoned just as quickly--Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.', 'United States', 'Jaume Collet-Serra', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg', 'https://youtube.com/embed/a1mcS4tKGNg', 'https://www.facebook.com/WarnerBrosPicturesLatinoamerica/?brand_redir=185370181482276', '2022-11-22 15:11:25');
INSERT INTO `movies` VALUES (6, 'tt13139228', 'My Policeman', 'Drama', 'The arrival of Patrick into Marion and Tom\'s home triggers the exploration of seismic events from 40 years previously.', 'United States', 'Michael Grandage', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wdbiMjXd4CxPfCx4r4Jfy8cGec0.jpg', 'https://youtube.com/embed/9XLPyPTWCJA', 'https://www.facebook.com/MyPolicemanMovie/', '2022-11-04 15:11:26');
INSERT INTO `movies` VALUES (7, 'tt8912936', 'DC League of Super-Pets', 'Animation', 'Krypto the Super-Dog and Superman are inseparable be.com/embedst friends, sharing the same superpowers and fighting crime side by side in Metropolis. However, Krypto must master his own powers for a rescue mission when Superman is kidnapped.', 'United States', 'Jared Stern', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r7XifzvtezNt31ypvsmb6Oqxw49.jpg', 'https://youtube.com/embed/1jkw2JPCl18', 'https://www.facebook.com/DCLeagueOfSuperPets/', '2022-11-04 15:11:27');
INSERT INTO `movies` VALUES (8, 'tt1745960', 'Top Gun: Maverick', 'Action', 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.', 'United States', 'Jim Cash', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', 'https://youtube.com/embed/zzBIzYmxatU', 'https://www.facebook.com/groups/topgunfans/', '2022-09-04 15:11:28');
INSERT INTO `movies` VALUES (9, 'tt10648342', 'Thor: Love and Thunder', 'Action', 'Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.', 'United States', 'Taika Waititi', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg', 'https://youtube.com/embed/9jrffoywRUU', 'https://www.facebook.com/thoravengerss/', '2022-09-04 15:11:29');
INSERT INTO `movies` VALUES (10, 'tt4154796', 'Avengers: Endgame', 'Action', 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.', 'United States', '', 'https://lumiere-a.akamaihd.net/v1/images/image_1e5c5703.jpeg', 'https://youtube.com/embed/PyakRSni-c0', 'https://www.facebook.com/AvengersEndgameTheMovie/', '2019-09-04 15:11:30');
INSERT INTO `movies` VALUES (11, 'tt12593682', 'Bullet Train', 'Comedy', 'Five assassins aboard a swiftly-moving bullet train find out that their missions have something in common.', 'United States', 'David Leitch', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg', 'https://youtube.com/embed/0IOsk2Vlc4o', 'https://www.facebook.com/bullettrainmovie/', '2022-09-04 15:11:31');
INSERT INTO `movies` VALUES (12, 'tt0816692', 'Interstellar', 'Sci-Fi', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', 'United States', 'Christopher Nolan', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'https://youtube.com/embed/UoSSbmD9vqc', 'https://www.facebook.com/fanclubinterstellar/', '2014-09-04 15:11:32');
INSERT INTO `movies` VALUES (13, 'tt10731256', 'Don\'t Worry Darling', 'Drama', 'A 1950s housewife living with her husband in a utopian experimental community be.com/embedgins to worry that his glamorous company could be.com/embed hiding disturbing secrets.', 'United States', 'Olivia Wilde', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/60hrKYVq6Y1QRJeHNbYo3tHDcUd.jpg', 'https://youtube.com/embed/FgmnKsED-jU', 'https://twitter.com/dontworrydarlin', '2022-07-04 15:11:33');
INSERT INTO `movies` VALUES (14, 'tt10731256', 'The Lord of the Rings: The Fellowship of the Ring', 'Action', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'United States', 'Peter Jackson', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', 'https://youtube.com/embed/V75dMMIW2B4', 'https://www.facebook.com/lordoftheringstrilogy/', '2001-07-04 15:11:34');
INSERT INTO `movies` VALUES (15, 'tt14109724', 'Ticket to Paradise', 'Comedy', 'A divorced couple teams up and travels to Bali to stop their daughter from making the same mistake they think they made 25 years ago.', 'United States', 'Ol Parker', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1tzERH50P5c2mFWtLbgixzLZS1L.jpg', 'https://youtube.com/embed/hkP4tVTdsz8', 'https://www.facebook.com/tickettoparadise/', '2022-07-04 15:11:35');
INSERT INTO `movies` VALUES (16, 'tt3758814', 'The Ice Road', 'Comedy', 'After a remote diamond mine collapses in far northern Canada, a \'big-rig\' ice road driver must lead an impossible rescue mission over a frozen lake to save the trapped miners.', 'United States', 'Jonathan Hensleigh', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pj6UQPrtmC0snzPeU1HUhGWTgz6.jpg', 'https://youtube.com/embed/Dj-2mdYUW-A', 'https://www.facebook.com/profile.php?id=100064511146677&paipv=0&eav=AfYaJw381yyPWczETM70MTPhlF-2RY_FFXLqjoJlrE_HQjOx5B4EUXlvJ8_MCVpAeAg', '2021-07-04 15:11:36');
INSERT INTO `movies` VALUES (17, 'tt5164214', 'Ocean\'s Eight', 'Thriller', 'Debbie Ocean gathers an all-female crew to attempt an impossible heist at New York City\'s yearly Met Gala.', 'United States', 'Gary Ross', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/MvYpKlpFukTivnlBhizGbkAe3v.jpg', 'https://youtube.com/embed/KWzEaDxEo_s', 'https://www.instagram.com/oceans8movie/?hl=es', '2018-07-04 15:11:37');
INSERT INTO `movies` VALUES (18, 'tt0762125', 'Planet 51', 'Animation', 'An alien civilization is invaded by Astronaut Chuck Baker, who be.com/embedlieves that the planet was uninhabited. Wanted by the military, Baker must get back to his ship be.com/embedfore it goes into orbit without him.', 'United States', 'Jorge Blanco', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/x7Itcg3ZdExKwdKguy73WPEqosW.jpg', 'https://youtube.com/embed/Zae2UJ_qCH0', 'https://www.facebook.com/planet51fanclub/', '2009-07-04 15:11:38');
INSERT INTO `movies` VALUES (19, 'tt5113044', 'Minions: The Rise of Gru', 'Animation', 'The untold story of one twelve-year-old\'s dream to be.com/embedcome the world\'s greatest supervillain.', 'United States', 'Kyle Balda', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg', 'https://youtube.com/embed/6DxjJzmYsXo', 'https://twitter.com/minion_fan4life', '2022-07-04 15:11:39');
INSERT INTO `movies` VALUES (20, 'tt1877830', 'The Batman', 'Action', 'When a sadistic serial killer be.com/embedgins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption and question his family\'s involvement.', 'United States', 'Matt Reeves', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/74xTEgt7R36Fpooo50r9T25onhq.jpg', 'https://youtube.com/embed/IqRRLA6pZvo', 'https://www.facebook.com/TheBatman/', '2022-04-04 15:11:40');
INSERT INTO `movies` VALUES (21, 'tt10872600', 'Spider-Man: No Way Home', 'Action', 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be.com/embed Spider-Man', 'United States', 'Jon Watts', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg', 'https://youtube.com/embed/ldMn-1iQzKE', 'https://www.facebook.com/MarvelStudiosSpiderMan/', '2021-04-04 15:11:41');
INSERT INTO `movies` VALUES (22, 'tt0111161', 'The Shawshank Redemption', 'Drama', 'Two imprisoned men bond over a numbe.com/embedr of years, finding solace and eventual redemption through acts of common decency.', 'United States', 'Frank Darabont', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'https://youtube.com/embed/vPIm7yl6EYY', '', '1994-05-04 15:11:42');
INSERT INTO `movies` VALUES (23, 'tt9253284', 'Andor', 'Sci-Fi', 'Prequel series to Star Wars\' \'Rogue One\'. In an era filled with danger, deception and intrigue, Cassian will embark on the path that is destined to turn him into a Rebe.com/embedl hero.', 'United States', 'Tony Gilroy', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lH2HddCYXXNRGomYIby7ZYE8uKL.jpg', 'https://youtube.com/embed/mhmMQjPMsys', 'https://www.facebook.com/groups/1651062951836356/?paipv=0&eav=AfYhQGNP9ddS5-9dagKAn-po9BtscMaYPxR23UAEfP1HkM75Jl5sNuX-SBb3E1B-13c&_rdr', '2022-05-04 15:11:43');
INSERT INTO `movies` VALUES (24, 'tt15474916', 'Smile', 'Sci-Fi', 'After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can\'t explain. Rose must confront her troubling past in order to survive and escape her horrifying new reality.', 'United States', 'Parker Finn', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg', '', 'https://youtu.be/yhKiQGJop_8', '2022-05-12 15:11:44');
INSERT INTO `movies` VALUES (25, 'tt9288822', 'The Wonder', 'Sci-Fi', 'A tale of two strangers who transform each other\'s lives, a psychological thriller, and a story of love pitted against evil.', 'United States', 'Sebastián Lelio', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/npBvD1rRQHYGrxuwr2OrzXLso1w.jpg', 'https://youtube.com/embed/htybz7XscIY', 'https://www.facebook.com/groups/4843118517/', '2022-07-12 15:11:45');
INSERT INTO `movies` VALUES (27, 'tt0910970', 'WALL·E', 'Animation', 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.', 'United States', 'Andrew Stanton', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg', 'https://youtube.com/embed/qF7p4lZ00RA', 'https://www.facebook.com/profile.php?id=100069545325292', '2008-07-12 15:11:47');
INSERT INTO `movies` VALUES (28, 'tt1596342', 'Disenchanted', 'Animation', 'Fifteen years after her happily ever after, Giselle questions her happiness, inadvertently turning the lives of those in the real world and Andalasia upside down in the process.', 'United States', 'Adam Shankman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zsZbtW3WhWbutpPzfq8Eieeqguj.jpg', 'https://youtube.com/embed/dRuwjZJ-DQw', 'https://www.facebook.com/groups/2269431710005171/', '2022-07-12 15:11:48');
INSERT INTO `movies` VALUES (29, 'tt1630029', 'Avatar: The Way of Water', 'Fantasy', 'Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their planet.', 'United States', 'James Cameron', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', 'https://youtube.com/embed/d9MyW72ELq0', 'https://www.facebook.com/groups/541651900664435/', '2022-12-12 09:15:49');
INSERT INTO `movies` VALUES (30, 'tt13320662', 'Slumbe.com/embedrland', 'Fantasy', 'A young girl discovers a secret map to the dreamworld of Slumbe.com/embedrland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, with the hope that she will be.com/embed able to see her late father again.', 'United States', 'Francis Lawrence', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f18kgonrgr8YvEuvshExS4XBGL8.jpg', 'https://youtube.com/embed/FBnkVJslRGo', '', '2022-11-12 09:15:50');
INSERT INTO `movies` VALUES (31, 'tt11138512', 'The Northman', 'Fantasy', 'A young Viking prince is on a quest to avenge his father\'s murder.', 'United States', 'Robe.com/embedrt Eggers', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg', 'https://youtu,/oMSdFM12hOw', 'https://www.facebook.com/TheNorthmanFilm/', '2022-04-12 09:15:51');
INSERT INTO `movies` VALUES (32, 'tt9419884', 'Doctor Strange in the Multiverse of Madness', 'Fantasy', 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.', 'United States', 'Sam Raimi', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg', 'https://youtube.com/embed/Rt_UqUm38BI', 'https://www.facebook.com/DoctorStrangebe.com/embedstFanPage/', '2022-05-06 09:15:52');
INSERT INTO `movies` VALUES (33, 'tt9764362', 'The Menu', 'Thriller', 'A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.', 'United States', 'Mark Mylod', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3R3dopFTwneJVPW3ubcrnoPfI05.jpg', 'https://youtube.com/embed/CAWZMssP3gM', 'https://www.facebook.com/TheMenuFilm/', '2022-11-18 09:15:53');
INSERT INTO `movies` VALUES (34, 'tt8415836', 'Guillermo del Toro\'s Cabinet of Curiosities', 'Thriller', 'Bizarre nightmares unfold in eight tales of terror in a visually stunning, spine-tingling horror collection curated by Guillermo del Toro.', 'United States', 'Guillermo del Toro', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/a91e9hpWwfCqxJI4xM9Q2RhuxgI.jpg', 'https://youtube.com/embed/E3E1URhCR60', 'https://www.facebook.com/NetflixColombia/?brand_redir=6275848869', '2022-11-18 09:15:54');
INSERT INTO `movies` VALUES (35, 'tt15791034', 'Barbarian', 'Thriller', 'A woman staying at an Airbnb discovers that the house she has rented is not what it seems.', 'United States', 'Zach Cregger', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg', 'https://youtube.com/embed/Dr89pmKrqkI', 'https://www.facebook.com/NetflixColombia/?brand_redir=6275848869', '2022-11-20 09:15:55');
INSERT INTO `movies` VALUES (36, 'tt5834204', 'The Handmaid\'s Tale', 'Thriller', 'Set in a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship.', 'United States', 'Bruce Miller', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/cnkKQyRzoCMZliMaknTOXHqXKaz.jpg', 'https://youtube.com/embed/oTnhx_N7nro', 'https://www.facebook.com/handmaidsonhulu/', '1990-11-20 09:15:56');
INSERT INTO `movies` VALUES (37, 'tt9319668', '1899', 'Horror', 'Multinational immigrants traveling from the old continent to the new encounter a nightmarish riddle aboard a second ship adrift on the open sea.', 'United States', 'Jantje Friese', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2QK8tIXafyiz93PvAbKxxfK2BLb.jpg', 'https://youtube.com/embed/soj6bA35ABk', 'https://www.facebook.com/profile.php?id=100067616590743', '2022-11-20 09:13:57');
INSERT INTO `movies` VALUES (38, 'tt10403420', 'Terrifier 2', 'Horror', 'After be.com/embeding resurrected by a sinister entity, Art the Clown returns to the timid town of Miles County where he targets a teenage girl and her younger brother on Halloween night.', 'United States', 'Damien Leone', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/b6IRp6Pl2Fsq37r9jFhGoLtaqHm.jpg', 'https://youtube.com/embed/6KkONLf_ZKU', 'https://www.facebook.com/TerrifierFilm/', '2022-06-20 09:13:58');
INSERT INTO `movies` VALUES (39, 'tt13560574', 'X', 'Horror', 'In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.', 'United States', 'Ti West', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/A7YPhQKdcr6XB1kCUdS4tHifYWd.jpg', 'https://youtube.com/embed/Awg3cWuHfoc', 'https://www.facebook.com/Xtheshortmovie/', '2022-03-18 09:13:59');
INSERT INTO `movies` VALUES (40, 'tt10954984', 'Nope', 'Horror', 'The residents of a lonely gulch in inland California be.com/embedar witness to an uncanny and chilling discovery.', 'United States', 'Jordan Peele', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg', 'https://youtube.com/embed/sCdHaufz0gc', 'https://www.facebook.com/nopemovie/', '2022-07-18 09:13:60');
INSERT INTO `movies` VALUES (41, 'tt18925334', 'Pearl', 'Horror', 'In 1918, a young woman on the brink of madness pursues stardom in a desperate attempt to escape the drudgery, isolation and lovelessness of life on her parents\' farm.', 'United States', 'Ti West', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/inxOR04CQXFVIKvn6cNu99d9Rg9.jpg', 'https://youtube.com/embed/L5PW5r3pEOg', 'https://www.instagram.com/pearl._.harbor/?hl=es', '2022-09-18 09:13:61');
INSERT INTO `movies` VALUES (42, 'tt8291284', 'The Peripheral', 'Mistery', 'Set in the future when technology has subtly altered society, a woman discovers a secret connection to an alternate reality as well as a dark future of her own.', 'United States', 'Jack Reynor', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ccBe5BVeibdBEQU7l6P6BubajWV.jpg', 'https://youtube.com/embed/RSaWHbCSmRI', 'https://mobile.twitter.com/theperipheralpv', '2022-09-18 09:13:62');
INSERT INTO `movies` VALUES (43, 'tt9411972', 'Where the Crawdads Sing', 'Mistery', 'A woman who raised herself in the marshes of the Deep South be.com/embedcomes a suspect in the murder of a man with whom she was once involved.', 'United States', 'Olivia Newman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6h5OCqRnWH7Dcm4IeP4JypBdtuI.jpg', 'https://youtube.com/embed/PY3808Iq0Tg', 'https://www.facebook.com/CrawdadsMovie/', '2022-07-18 09:13:63');
INSERT INTO `movies` VALUES (44, 'tt10304142', 'Amsterdam', 'Mistery', 'In the 1930s, three friends witness a murder, are framed for it, and uncover one of the most outrageous plots in American history.', 'United States', 'David O. Russell', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/chCrPG0LJeilfJwsWPAfmWiJI2T.jpg', 'https://youtube.com/embed/GLs2xxM0e78', 'https://www.instagram.com/amsterdammovie/?hl=es', '2022-07-10 09:13:65');
INSERT INTO `movies` VALUES (46, 'tt7846844', 'Enola Holmes', 'Mistery', 'When Enola Holmes-Sherlock\'s teen sister-discovers her mother is missing, she sets off to find her, be.com/embedcoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy around a mysterious young Lord.', 'United States', 'Harry Bradbe.com/embeder', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/riYInlsq2kf1AWoGm80JQW5dLKp.jpg', 'https://youtube.com/embed/DkLS_VwPGzQ', 'https://www.facebook.com/enolaholmes2/', '2020-09-23 09:13:66');
INSERT INTO `movies` VALUES (47, 'tt11198330', 'House of the Dragon', 'Adventure', 'An internal succession war within House Targaryen at the height of its power, 172 years be.com/embedfore the birth of Daenerys Targaryen.', 'United States', 'Ryan J. Condal', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg', 'https://youtube.com/embed/fNwwt25mheo', 'https://www.facebook.com/profile.php?id=100070016807275', '2022-10-23 09:13:67');
INSERT INTO `movies` VALUES (48, 'tt0944947', 'Game of Thrones', 'Adventure', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after be.com/embeding dormant for millennia.', 'United States', 'David be.com/embednioff', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/d1BUy1ubcs0Ix4YYnn7iuj0AJhn.jpg', 'https://youtube.com/embed/BpJYNVhGf1s', 'https://www.facebook.com/Game.Of.Thrones.Forever/', '2011-10-23 09:13:68');
INSERT INTO `movies` VALUES (49, 'tt0436992', 'Doctor Who', 'Adventure', 'The further adventures in time and space of the alien adventurer known as the Doctor and their companions from planet Earth.', 'United Kingdom', 'Sydney Newman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sz4zF5z9zyFh8Z6g5IQPNq91cI7.jpg', 'https://youtube.com/embed/7hRy2N2CMhQ', 'https://www.facebook.com/whoniversefandomcreations/', '2005-10-23 09:13:69');

SET FOREIGN_KEY_CHECKS = 1;
